if (!require(devtools) )
  install.pack.aghoo.("devtools")
if (! require(leaflet) || ! require(DT))
  install.pack.aghoo.("leaflet", "DT", repos="https://cran.rstudio.com")
shiny::runApp("./engines", host="0.0.0.0", port=5930)
